version: '3.9'

services:
  # Database service (MariaDB)
  db:
    container_name: db
    image: mariadb:10.6.4-focal
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - wpnet

  # Wordpress service (Wordpress)
  wp:
    depends_on:
      - db
    container_name: wp
    image: wordpress:latest
    restart: always
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PORT=${MYSQL_PORT}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
    ports:
      - ${WORDPRESS_PORT}:80
    volumes:
      - ./app:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - wpnet

networks:
  wpnet:
    driver: bridge